name: Lint, Build

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format
        run: |
          if [ "$(gofmt -d -e . | wc -l)" -gt 0 ]; then
            gofmt -d -e .
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container image
        run: |
          docker build -t sudomateo/todo:latest .
      - name: Log in to Docker Hub
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push container image to Docker Hub
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: |
          docker push sudomateo/todo:latest
